packages:
  - 'packages/*'
  - 'services/*'
allowBuilds:
  core-js: false
  rolldown: false
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@atproto/lex-client@0.3.0'
  - '@atproto/lex-installer@0.1.9'
  - '@atproto/lex-password-session@0.1.8'
  - '@atproto/lex-resolver@0.2.2'
  - '@atproto/lex@0.3.0'
